export const projectsList = [
  {
    id: 1,
    name: "AI professionals Chat Application",
    description:
      "The Agent Mode in HelloScribe is an Autonomous Reasoning Agent (ARA). This is an advanced type of artificial intelligence that performs various writing, thinking, and research tasks using inputs from a human expert.",
    image: "/images/helloscribe1.png",
    mobileImage: "/images/helloscribe2.png",
    link: "https://app.helloscribe.ai/",
    GitHub: "https://github.com/fragrance49/helloscribe-frontend",
    project: "books-app",
    tools: ["Vue3, Node.js, Flask"],
  },
  {
    id: 2,
    name: "Forecast website",
    description:
      "It is a clone application made with the UI designs of the phone application of Uber Eats.",
    image: "/images/stableforecast-1.png",
    mobileImage: "/images/stableforecast-2.png",
    link: "https://stableforecast.com/",
    GitHub: "https://github.com/fragrance49/stable-forecast",
    project: "stableforecast",
    tools: ["Django"],
  },
  {
    id: 3,
    name: "Leetcode Clone",
    description:
      "It is a clone application made with the user interface designs of the Leetcode website developed in a full stack.",
    image: "/images/Leetcode_Clone_Screenshot_Small.png",
    mobileImage: "/images/Leetcode_Clone_Screenshot_Small.png",
    link: "https://react-leetcode-clone.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/React-Leetcode-Clone",
    project: "leetcode-clone",
    tools: ["React"],
  },
  {
    id: 5,
    name: "Trello Clone",
    description:
      "It is a clone application that displays the improved user interface of the trello website and the status of the tasks added to the user using ChatGPT.",
    image: "/images/Trello_Clone_Screenshot_Small.png",
    mobileImage: "/images/Trello_Clone_Screenshot_Small.png",
    link: "https://react-trello-clone-eight.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/React-Trello-Clone",
    project: "trello-clone",
    tools: ["React"],
  },
  {
    id: 6,
    name: "Pizza Shop",
    description:
      "This site allows you to select the pizza you want to order, select the size and the ingredients to be added, and place an order.",
    image: "/images/Pizzashop_Screenshot_Small.png",
    mobileImage: "/images/Pizzashop_Screenshot_Small.png",
    link: "https://react-pizzashop.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/React-Pizzashop",
    project: "pizza-shop",
    tools: ["React"],
  },
  {
    id: 7,
    name: "Movie Application",
    description:
      "This site is a full stack site with a stylish design that shows the ratings and likes of today's current series and movies.",
    image: "/images/Movie_App_Screenshot.png",
    mobileImage: "/images/Movie_App_Screenshot_Small.png",
    link: "https://react-movie-application.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/React-Movie-Application",
    project: "movie-app",
    tools: ["React"],
  },
  {
    id: 10,
    name: "Summarizer Website",
    description:
      "This site is an article extractor and summarizer. It is enough to paste the link of the site you want to extract the summary of the article in the box.",
    image: "/images/Summarizer_Website_Screenshot_Small.png",
    mobileImage: "/images/Summarizer_Website_Screenshot_Small.png",
    link: "https://react-summarizer-website.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/React-Summarizer-Website",
    project: "summarizer-website",
    tools: ["React"],
  },
  {
    id: 11,
    name: "Disney+ Clone",
    description:
      "It was based on the UI design of Disney plus, and you can see the movies and the latest series that are newly released or about to be released.",
    image: "/images/Disneyplus_Clone_Screenshot.png",
    mobileImage: "/images/Disneyplus_Clone_Screenshot_Small.png",
    link: "https://disneyplus-clone-ca370.web.app",
    GitHub: "https://github.com/eraydmrcoglu/Disney-plus-Clone",
    project: "disney-plus-clone",
    tools: ["React"],
  },
  {
    id: 12,
    name: "Spotify Clone",
    description:
      "Based on Spotify's UI design. You can play the music you want simultaneously by opening the spotify desktop application.",
    image: "/images/Spotify_Clone_Screenshot.png",
    mobileImage: "/images/Spotify_Clone_Screenshot_Small.png",
    link: "https://spotify-clone-eta-seven.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Spotify-Clone",
    project: "spotify-clone",
    tools: ["React"],
  },
  {
    id: 13,
    name: "Netflix Clone",
    description:
      "It was based on Netflix's UI design. A site where you can easily find newly released, popular or recommended movies and series.",
    image: "/images/Netflix_Clone_Screenshot.png",
    mobileImage: "/images/Netflix_Clone_Screenshot_Small.png",
    link: "",
    GitHub: "https://github.com/eraydmrcoglu/Netlflix-Clone",
    project: "netflix-clone",
    tools: ["React"],
  },
  {
    id: 15,
    name: "Tesla Clone",
    description:
      "This site consists of a similar study of the UI design of the Tesla website.",
    image: "/images/Tesla_Clone_Screenshot.png",
    mobileImage: "/images/Tesla_Clone_Screenshot_Small.png",
    link: "https://tesla-clone-site1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Tesla-Clone",
    project: "tesla-clone",
    tools: ["React"],
  },
  {
    id: 16,
    name: "Metaverse Website",
    description:
      "This site is a responsive site design that introduces the metaverse universe.",
    image: "/images/Metaverse_Site_Screenshot.png",
    mobileImage: "/images/Metaverse_Site_Screenshot_Small.png",
    link: "https://metaverse-site1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Metaverse-Website",
    project: "metaverse",
    tools: ["React"],
  },
  {
    id: 17,
    name: "Rent a Car Website",
    description:
      "On this site, easy access to the vehicle they want is offered for those who need daily car rental.",
    image: "/images/Rent_Car_Site_Screenshot.png",
    mobileImage: "/images/Rent_Car_Site_Screenshot_Small.png",
    link: "https://react-rent-car-site.vercel.app/home",
    GitHub: "https://github.com/eraydmrcoglu/React-Rent-Car-Site",
    project: "rent-car",
    tools: ["React"],
  },
  {
    id: 18,
    name: "Food Ordering App",
    description:
      "This site is a site that aims to choose the food you want to order and bring it to you as soon as possible.",
    image: "/images/Food_Ordering_App_Screenshot.png",
    mobileImage: "/images/Food_Ordering_App_Screenshot_Small.png",
    link: "https://superb-phoenix-78f957.netlify.app/home",
    GitHub: "https://github.com/eraydmrcoglu/React-Food-Ordering-App",
    project: "food-ordering-app",
    tools: ["React"],
  },
  {
    id: 20,
    name: "Weather App",
    description:
      "On this site, it shows the weather conditions of the day and other days of the week and leaves a good impression with its stylish design.",
    image: "/images/Weather_App_Screenshot.png",
    mobileImage: "/images/Weather_App_Screenshot_Small.png",
    link: "https://weather-react-app1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Weather-App",
    project: "weather-app",
    tools: ["React"],
  },
  {
    id: 21,
    name: "BMI Calculator",
    description:
      "Body mass index is calculated by dividing body mass by the square of the height in meters. This makes the calculation easy on the site I made.",
    image: "/images/Bmi_Calculator_Screenshot.png",
    mobileImage: "/images/Bmi_Calculator_Screenshot_Small.png",
    link: "https://react-bmi-calculator1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/BMI-Calculator",
    project: "bmi-calculator",
    tools: ["React"],
  },
  {
    id: 22,
    name: "Rock Paper Scissors Game",
    description: "Rock-Paper-Scissors game played against the computer.",
    image: "/images/Rock_Paper_Scissors_Screenshot.png",
    mobileImage: "/images/Rock_Paper_Scissors_Screenshot_Small.png",
    link: "https://rock-paper-scissors-game1.vercel.app",
    GitHub:
      "https://github.com/eraydmrcoglu/Projects/tree/main/rock-paper-scissors-game",
    project: "rock-paper-scissors-game",
    tools: ["react"],
  },
  {
    id: 23,
    name: "Card Guessing Game",
    description:
      "As the name suggests, it is a game of finding the pairs of cards by guessing.",
    image: "/images/Card_Guessing_Game_Screenshot.png",
    mobileImage: "/images/Card_Guessing_Game_Screenshot_Small.png",
    link: "https://react-card-guessing-game1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Card-Guessing-Game",
    project: "card-guessing-game",
    tools: ["react"],
  },
  {
    id: 24,
    name: "Typing Speed App",
    description:
      "Today, there may be jobs where software workers need to type fast. Thanks to this application, he can gain the habit of typing fast by aiming to write the words that will come randomly in 60 seconds and reach the highest score.",
    image: "/images/Typing_Speed_Screenshot.png",
    mobileImage: "/images/Typing_Speed_Screenshot_Small.png",
    link: "https://typing-speed-app.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Typing-Speed-App",
    project: "typing-speed",
    tools: ["React"],
  },
];
